name: Build + Publish templates.json file
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v2
        
      - name: Set up Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies 📥
        run: |
          python -m pip install --upgrade pip
          # If you have any dependencies, install them here

      - name: Run make command 🔨
        run: make

      - name: Commit and push generated files ⤴️
        run: |
          git config --global user.name "Liss-Bot"
          git config --global user.email "alicia-gh-bot@mail.as93.net"
          git add .
          git commit -m "Generates templates.json [skip ci]"
          git push
